<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="24489" started-at="2018-12-14T06:43:47Z" finished-at="2018-12-14T06:44:12Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="24489" started-at="2018-12-14T06:43:47Z" finished-at="2018-12-14T06:44:12Z">
      <class name="DD2.DummyTestC">
        <test-method status="FAIL" signature="DTestC1()[pri:3, instance:DD2.DummyTestC@6e1567f1]" name="DTestC1" duration-ms="0" started-at="2018-12-14T12:14:12Z" finished-at="2018-12-14T12:14:12Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at DD1.DummyTestBase1.takeScreenshot(DummyTestBase1.java:135)
	at DD2.DummyTestC.DTestC1(DummyTestC.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DTestC1 -->
      </class> <!-- DD2.DummyTestC -->
      <class name="DD2.DummyTestB">
        <test-method status="PASS" signature="Setup()[pri:0, instance:DD2.DummyTestB@59494225]" name="Setup" is-config="true" duration-ms="157" started-at="2018-12-14T12:13:47Z" finished-at="2018-12-14T12:13:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="PASS" signature="DTestB1()[pri:1, instance:DD2.DummyTestB@59494225]" name="DTestB1" duration-ms="22729" started-at="2018-12-14T12:13:47Z" finished-at="2018-12-14T12:14:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DTestB1 -->
        <test-method status="PASS" signature="DTestB2()[pri:2, instance:DD2.DummyTestB@59494225]" name="DTestB2" duration-ms="1745" started-at="2018-12-14T12:14:10Z" finished-at="2018-12-14T12:14:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DTestB2 -->
      </class> <!-- DD2.DummyTestB -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
